### ISSUE TITLE
Platform error climate.adax - No module named 'sanction'

### ISSUE THREAD

**Issue by cortado** [Danielhiversen/home-assistant_custom_components#1]
Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:326 
Integration: Hass.io (documentation, issues) 
First occurred: 11:32:40 PM (1 occurrences) 
Last logged: 11:32:40 PM

Platform error climate.adax - No module named 'sanction' Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See ?, line ?).

**Comment by Danielhiversen** [comment]
Run:
`pip install sanction `
