### ISSUE TITLE
Authentication fail

### ISSUE THREAD

**Issue by Klaveness** [Danielhiversen/home-assistant_custom_components#2]
On the fist run, home assistant complained about the sanction package missing and would not restart. I then forced the restart by restarting the container and it was fine (home assisstant installed it).

I then ran into an authentication issue. In the app, my client id is just four digits, not six. It might be due to authenticating by e-mail and password? I inserted a _LOGGER.debug statement above the line and client_id and password are correct.

 `File "/config/custom_components/adax/climate.py", line 162, in _request
    self._oauth_client.request_token(grant_type='password', username=self._client_id, password=self._client_secret)`
(...)
` File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: {"error": "invalid_request"}`

Update
Got this if I put 00 in front of my user_id:
`
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: {"error": "invalid_grant"}`

Upsate 2:
I see, now, that one has to add credentials in the new 3.5.1 app. However, it is still not available for android. Will retry when this is available

**Comment by Danielhiversen** [comment]
Yes, you currently need ios to get the credentials.
